2021-03-13 18:35:58 INFO run.py:219 GNS3 server version 2.2.19
2021-03-13 18:35:58 INFO run.py:221 Copyright (c) 2007-2021 GNS3 Technologies Inc.
2021-03-13 18:35:58 INFO run.py:224 Config file /home/saad/.config/GNS3/2.2/gns3_server.conf loaded
2021-03-13 18:35:58 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2021-03-13 18:35:58 INFO run.py:243 Running with Python 3.9.2 and has PID 1394
2021-03-13 18:35:58 INFO run.py:79 Current locale is en_US.UTF-8
2021-03-13 18:35:58 INFO web_server.py:318 Starting server on localhost:3080
2021-03-13 18:35:58 INFO __init__.py:62 Load controller configuration file /home/saad/.config/GNS3/2.2/gns3_controller.conf
2021-03-13 18:35:58 INFO __init__.py:66 Controller is starting
2021-03-13 18:35:58 INFO compute.py:64 Create compute local
2021-03-13 18:35:58 INFO compute.py:364 Connecting to compute 'local'
2021-03-13 18:35:58 INFO web_log.py:233 ::1 [13/Mar/2021:13:35:58 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:35:59 ERROR web_protocol.py:355 Error handling request
Traceback (most recent call last):
  File "/home/saad/.local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "/home/saad/.local/lib/python3.9/site-packages/aiohttp/http_parser.py", line 264, in feed_data
    msg = self.parse_message(self._lines)
  File "/home/saad/.local/lib/python3.9/site-packages/aiohttp/http_parser.py", line 437, in parse_message
    raise BadStatusLine(method)
aiohttp.http_exceptions.BadStatusLine: /version
2021-03-13 18:35:59 INFO notification_handler.py:50 New client has connected to compute WebSocket
2021-03-13 18:35:59 INFO compute.py:434 Connected to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-03-13 18:35:59 INFO web_log.py:233 ::1 [13/Mar/2021:13:35:59 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:35:59 INFO notification_handler.py:73 New client has connected to controller WebSocket
2021-03-13 18:35:59 INFO web_log.py:233 ::1 [13/Mar/2021:13:35:59 +0000] "GET /v2/templates HTTP/1.1" 200 17094 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:35:59 INFO web_log.py:233 ::1 [13/Mar/2021:13:35:59 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:35:59 INFO web_log.py:233 ::1 [13/Mar/2021:13:35:59 +0000] "GET /v2/appliances?symbol_theme=Affinity-circle-gray HTTP/1.1" 200 786188 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:35:59 INFO web_log.py:233 ::1 [13/Mar/2021:13:35:59 +0000] "GET /v2/projects HTTP/1.1" 200 22415 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:35:59 INFO web_log.py:233 ::1 [13/Mar/2021:13:35:59 +0000] "GET /v2/projects HTTP/1.1" 200 22415 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:07 INFO project.py:78 Project b333129b-60dd-46eb-8b07-e2f7fe46f72d with path '/home/saad/GNS3/projects/untitled' created
2021-03-13 18:36:07 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:07 +0000] "POST /v2/compute/projects HTTP/1.1" 201 303 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:07 INFO nat.py:51 NAT node 'NAT1' configured to use NAT interface 'virbr0'
2021-03-13 18:36:07 INFO base_node.py:655 Starting new uBridge hypervisor localhost:44263
2021-03-13 18:36:07 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:44263']
2021-03-13 18:36:07 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/untitled/project-files/builtin/20a98038-f523-4ca4-a774-094360f7419c/ubridge.log
2021-03-13 18:36:07 INFO hypervisor.py:179 ubridge started PID=1413
2021-03-13 18:36:07 INFO base_node.py:658 Hypervisor localhost:44263 has successfully started
2021-03-13 18:36:08 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:44263 after 0.1022 seconds
2021-03-13 18:36:08 INFO cloud.py:215 Cloud "NAT1" [20a98038-f523-4ca4-a774-094360f7419c] has been created
2021-03-13 18:36:08 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:07 +0000] "POST /v2/compute/projects/b333129b-60dd-46eb-8b07-e2f7fe46f72d/nat/nodes HTTP/1.1" 201 553 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:08 INFO docker_vm.py:1058 Docker container "debian-1" [68c70035-a3ec-4870-9496-70fc7a1d0ebd]: number of Ethernet adapters changed to 1
2021-03-13 18:36:08 INFO docker_vm.py:406 Docker container 'debian-1' [68c70035-a3ec-4870-9496-70fc7a1d0ebd] created
2021-03-13 18:36:08 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:08 +0000] "POST /v2/compute/projects/b333129b-60dd-46eb-8b07-e2f7fe46f72d/docker/nodes HTTP/1.1" 201 924 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:08 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:08 +0000] "POST /v2/compute/projects/b333129b-60dd-46eb-8b07-e2f7fe46f72d/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:08 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:08 +0000] "POST /v2/compute/projects/b333129b-60dd-46eb-8b07-e2f7fe46f72d/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:08 INFO docker_vm.py:960 Docker container 'debian-1' [68c70035-a3ec-4870-9496-70fc7a1d0ebd]: NIO UDP added to adapter 0
2021-03-13 18:36:08 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:08 +0000] "POST /v2/compute/projects/b333129b-60dd-46eb-8b07-e2f7fe46f72d/docker/nodes/68c70035-a3ec-4870-9496-70fc7a1d0ebd/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:08 INFO cloud.py:396 Cloud "NAT1" [20a98038-f523-4ca4-a774-094360f7419c]: NIO NIO UDP bound to port 0
2021-03-13 18:36:08 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:08 +0000] "POST /v2/compute/projects/b333129b-60dd-46eb-8b07-e2f7fe46f72d/nat/nodes/20a98038-f523-4ca4-a774-094360f7419c/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:08 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:08 +0000] "POST /v2/compute/projects/b333129b-60dd-46eb-8b07-e2f7fe46f72d/nat/nodes/20a98038-f523-4ca4-a774-094360f7419c/stop HTTP/1.1" 204 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:08 INFO docker_vm.py:533 Docker container 'debian-1' fix ownership, state = exited
2021-03-13 18:36:08 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:08 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:13 INFO docker_vm.py:793 Docker container 'debian-1' [debian:latest] stopped
2021-03-13 18:36:13 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:08 +0000] "POST /v2/compute/projects/b333129b-60dd-46eb-8b07-e2f7fe46f72d/docker/nodes/68c70035-a3ec-4870-9496-70fc7a1d0ebd/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:13 INFO base_node.py:331 Builtin: 'NAT1' [20a98038-f523-4ca4-a774-094360f7419c]: is closing
2021-03-13 18:36:13 INFO base_node.py:669 Stopping uBridge hypervisor localhost:44263
2021-03-13 18:36:13 INFO hypervisor.py:208 Stopping uBridge process PID=1413
2021-03-13 18:36:13 INFO base_node.py:331 Docker: 'debian-1' [68c70035-a3ec-4870-9496-70fc7a1d0ebd]: is closing
2021-03-13 18:36:13 INFO docker_vm.py:872 Docker container 'debian-1' [debian:latest] removed
2021-03-13 18:36:14 INFO cloud.py:248 Cloud "NAT1" [20a98038-f523-4ca4-a774-094360f7419c] has been closed
2021-03-13 18:36:14 INFO project.py:361 Project b333129b-60dd-46eb-8b07-e2f7fe46f72d with path '/home/saad/GNS3/projects/untitled' closed
2021-03-13 18:36:14 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:13 +0000] "POST /v2/compute/projects/b333129b-60dd-46eb-8b07-e2f7fe46f72d/close HTTP/1.1" 204 224 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:14 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:07 +0000] "DELETE /v2/projects/b333129b-60dd-46eb-8b07-e2f7fe46f72d HTTP/1.1" 204 210 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:14 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:14 +0000] "GET /v2/projects HTTP/1.1" 200 21793 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:14 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:14 +0000] "GET /v2/projects HTTP/1.1" 200 21793 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:14 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:14 +0000] "POST /v2/projects HTTP/1.1" 201 724 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:14 INFO project_handler.py:271 New client has connected to the notification stream for project ID '5d7af2a7-2aa9-49fb-b355-e529f3684dcc' (WebSocket method)
2021-03-13 18:36:14 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:14 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:17 INFO project.py:78 Project 5d7af2a7-2aa9-49fb-b355-e529f3684dcc with path '/home/saad/GNS3/projects/untitled' created
2021-03-13 18:36:17 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:17 +0000] "POST /v2/compute/projects HTTP/1.1" 201 303 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:17 INFO docker_vm.py:1058 Docker container "debian-1" [404267a4-1be5-4284-bfb5-321e86f0bae3]: number of Ethernet adapters changed to 1
2021-03-13 18:36:17 INFO docker_vm.py:406 Docker container 'debian-1' [404267a4-1be5-4284-bfb5-321e86f0bae3] created
2021-03-13 18:36:17 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:17 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/docker/nodes HTTP/1.1" 201 924 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:17 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:17 +0000] "POST /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/templates/d9eb10a9-711b-44a6-915f-b1e6dcd2423e HTTP/1.1" 201 1894 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:17 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:17 +0000] "PUT /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/docker/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3 HTTP/1.1" 200 929 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:17 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:17 +0000] "PUT /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3 HTTP/1.1" 200 1967 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:18 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:18 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:18 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:18 +0000] "PUT /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/docker/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3 HTTP/1.1" 200 929 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:18 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:18 +0000] "PUT /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3 HTTP/1.1" 200 1968 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:21 INFO nat.py:51 NAT node 'NAT1' configured to use NAT interface 'virbr0'
2021-03-13 18:36:21 INFO base_node.py:655 Starting new uBridge hypervisor localhost:33903
2021-03-13 18:36:21 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:33903']
2021-03-13 18:36:21 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/untitled/project-files/builtin/47b2d5b3-e210-4b97-ba4e-cf6638abb3c4/ubridge.log
2021-03-13 18:36:21 INFO hypervisor.py:179 ubridge started PID=1589
2021-03-13 18:36:21 INFO base_node.py:658 Hypervisor localhost:33903 has successfully started
2021-03-13 18:36:21 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:33903 after 0.1034 seconds
2021-03-13 18:36:21 INFO cloud.py:215 Cloud "NAT1" [47b2d5b3-e210-4b97-ba4e-cf6638abb3c4] has been created
2021-03-13 18:36:21 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:21 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nat/nodes HTTP/1.1" 201 553 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:21 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:21 +0000] "POST /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/templates/df8f4ea9-33b7-3e96-86a2-c39bc9bb649c HTTP/1.1" 201 1571 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:21 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:21 +0000] "PUT /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nat/nodes/47b2d5b3-e210-4b97-ba4e-cf6638abb3c4 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:21 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:21 +0000] "PUT /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/47b2d5b3-e210-4b97-ba4e-cf6638abb3c4 HTTP/1.1" 200 1644 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:21 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:21 +0000] "PUT /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nat/nodes/47b2d5b3-e210-4b97-ba4e-cf6638abb3c4 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:21 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:21 +0000] "PUT /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/47b2d5b3-e210-4b97-ba4e-cf6638abb3c4 HTTP/1.1" 200 1644 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:22 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:22 +0000] "PUT /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nat/nodes/47b2d5b3-e210-4b97-ba4e-cf6638abb3c4 HTTP/1.1" 200 558 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:22 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:22 +0000] "PUT /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/47b2d5b3-e210-4b97-ba4e-cf6638abb3c4 HTTP/1.1" 200 1644 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:23 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:23 +0000] "PUT /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/docker/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3 HTTP/1.1" 200 929 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:23 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:23 +0000] "PUT /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3 HTTP/1.1" 200 1968 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:23 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:23 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:29 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:29 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:29 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:29 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:29 INFO docker_vm.py:960 Docker container 'debian-1' [404267a4-1be5-4284-bfb5-321e86f0bae3]: NIO UDP added to adapter 0
2021-03-13 18:36:29 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:29 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/docker/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:29 INFO cloud.py:396 Cloud "NAT1" [47b2d5b3-e210-4b97-ba4e-cf6638abb3c4]: NIO NIO UDP bound to port 0
2021-03-13 18:36:29 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:36:29 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nat/nodes/47b2d5b3-e210-4b97-ba4e-cf6638abb3c4/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:29 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:29 +0000] "POST /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/links HTTP/1.1" 201 1197 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:29 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:29 +0000] "PUT /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/links/bdf12bd0-08fb-4ee6-8882-10c7109f3d54 HTTP/1.1" 201 1290 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:29 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:29 +0000] "PUT /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/links/bdf12bd0-08fb-4ee6-8882-10c7109f3d54 HTTP/1.1" 201 1371 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:32 INFO base_node.py:655 Starting new uBridge hypervisor localhost:46759
2021-03-13 18:36:32 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:46759']
2021-03-13 18:36:32 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/untitled/project-files/docker/404267a4-1be5-4284-bfb5-321e86f0bae3/ubridge.log
2021-03-13 18:36:32 INFO hypervisor.py:179 ubridge started PID=1661
2021-03-13 18:36:32 INFO base_node.py:658 Hypervisor localhost:46759 has successfully started
2021-03-13 18:36:32 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:46759 after 0.1034 seconds
2021-03-13 18:36:32 INFO docker_vm.py:499 Docker container 'debian-1' [debian:latest] started listen for telnet on 5000
2021-03-13 18:36:32 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:32 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/docker/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/start HTTP/1.1" 204 247 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:32 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:32 +0000] "POST /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/start HTTP/1.1" 200 1974 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:33 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:33 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:51 INFO base_node.py:669 Stopping uBridge hypervisor localhost:46759
2021-03-13 18:36:51 INFO hypervisor.py:208 Stopping uBridge process PID=1661
2021-03-13 18:36:51 INFO docker_vm.py:533 Docker container 'debian-1' fix ownership, state = running
2021-03-13 18:36:51 INFO docker_vm.py:793 Docker container 'debian-1' [debian:latest] stopped
2021-03-13 18:36:51 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:51 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/docker/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:36:51 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:51 +0000] "POST /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/stop HTTP/1.1" 200 1973 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:36:54 INFO web_log.py:233 ::1 [13/Mar/2021:13:36:54 +0000] "GET /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/files/etc/network/interfaces HTTP/1.1" 200 574 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:37:00 INFO web_log.py:233 ::1 [13/Mar/2021:13:37:00 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/files/project-files/docker/404267a4-1be5-4284-bfb5-321e86f0bae3/etc/network/interfaces HTTP/1.1" 200 226 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:37:00 INFO web_log.py:233 ::1 [13/Mar/2021:13:37:00 +0000] "POST /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/files/etc/network/interfaces HTTP/1.1" 201 239 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:37:02 INFO base_node.py:655 Starting new uBridge hypervisor localhost:39067
2021-03-13 18:37:02 INFO hypervisor.py:169 starting ubridge: ['/usr/bin/ubridge', '-H', 'localhost:39067']
2021-03-13 18:37:02 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/untitled/project-files/docker/404267a4-1be5-4284-bfb5-321e86f0bae3/ubridge.log
2021-03-13 18:37:02 INFO hypervisor.py:179 ubridge started PID=1837
2021-03-13 18:37:02 INFO base_node.py:658 Hypervisor localhost:39067 has successfully started
2021-03-13 18:37:02 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:39067 after 0.1025 seconds
2021-03-13 18:37:02 INFO docker_vm.py:499 Docker container 'debian-1' [debian:latest] started listen for telnet on 5000
2021-03-13 18:37:02 INFO web_log.py:233 ::1 [13/Mar/2021:13:37:02 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/docker/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/start HTTP/1.1" 204 247 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:37:02 INFO web_log.py:233 ::1 [13/Mar/2021:13:37:02 +0000] "POST /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/start HTTP/1.1" 200 1974 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:37:03 INFO web_log.py:233 ::1 [13/Mar/2021:13:37:03 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:39:33 INFO web_log.py:233 ::1 [13/Mar/2021:13:39:33 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nat/nodes/47b2d5b3-e210-4b97-ba4e-cf6638abb3c4/stop HTTP/1.1" 204 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:39:33 INFO base_node.py:669 Stopping uBridge hypervisor localhost:39067
2021-03-13 18:39:33 INFO hypervisor.py:208 Stopping uBridge process PID=1837
2021-03-13 18:39:33 INFO docker_vm.py:533 Docker container 'debian-1' fix ownership, state = running
2021-03-13 18:39:33 INFO docker_vm.py:793 Docker container 'debian-1' [debian:latest] stopped
2021-03-13 18:39:33 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:39:33 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/docker/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:39:33 INFO web_log.py:233 ::1 [13/Mar/2021:13:39:33 +0000] "POST /v2/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nodes/stop HTTP/1.1" 204 221 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:39:35 INFO notification_handler.py:82 Client has disconnected from controller WebSocket
2021-03-13 18:39:35 INFO server_handler.py:53 Start shutting down the server
2021-03-13 18:39:35 INFO web_log.py:233 127.0.0.1 [13/Mar/2021:13:39:35 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/nat/nodes/47b2d5b3-e210-4b97-ba4e-cf6638abb3c4/stop HTTP/1.1" 204 243 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:39:35 INFO web_log.py:233 ::1 [13/Mar/2021:13:39:35 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/docker/nodes/404267a4-1be5-4284-bfb5-321e86f0bae3/stop HTTP/1.1" 204 246 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:39:35 INFO base_node.py:331 Builtin: 'NAT1' [47b2d5b3-e210-4b97-ba4e-cf6638abb3c4]: is closing
2021-03-13 18:39:35 INFO base_node.py:669 Stopping uBridge hypervisor localhost:33903
2021-03-13 18:39:35 INFO hypervisor.py:208 Stopping uBridge process PID=1589
2021-03-13 18:39:35 INFO base_node.py:331 Docker: 'debian-1' [404267a4-1be5-4284-bfb5-321e86f0bae3]: is closing
2021-03-13 18:39:35 INFO docker_vm.py:872 Docker container 'debian-1' [debian:latest] removed
2021-03-13 18:39:35 INFO cloud.py:248 Cloud "NAT1" [47b2d5b3-e210-4b97-ba4e-cf6638abb3c4] has been closed
2021-03-13 18:39:35 INFO project.py:361 Project 5d7af2a7-2aa9-49fb-b355-e529f3684dcc with path '/home/saad/GNS3/projects/untitled' closed
2021-03-13 18:39:35 INFO web_log.py:233 ::1 [13/Mar/2021:13:39:35 +0000] "POST /v2/compute/projects/5d7af2a7-2aa9-49fb-b355-e529f3684dcc/close HTTP/1.1" 204 224 "-" "Python/3.9 aiohttp/3.6.2"
2021-03-13 18:39:35 INFO web_server.py:113 Closing 2 websocket connections...
2021-03-13 18:39:35 INFO web_log.py:233 ::1 [13/Mar/2021:13:39:35 +0000] "POST /v2/shutdown HTTP/1.1" 201 194 "-" "GNS3 QT Client v2.2.19"
2021-03-13 18:39:35 INFO compute.py:460 Connection closed to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-03-13 18:39:35 INFO project_handler.py:280 Client has disconnected from notification stream for project ID '5d7af2a7-2aa9-49fb-b355-e529f3684dcc' (WebSocket method)
2021-03-13 18:39:35 INFO notification_handler.py:59 Client has disconnected from compute WebSocket
2021-03-13 18:39:35 INFO __init__.py:130 Controller is stopping
2021-03-13 18:39:35 INFO run.py:272 Remove PID file /home/saad/.config/GNS3/2.2/gns3_server.pid
